services:
  frontend:
    build:
      args:
        - API_URL=http://127.0.0.1:8000/api/v1
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_URL=https://imperka.tech/api/v1
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - secret_key
        - password
        - username
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=default
    ports:
      - "27016:27017"
    volumes:
      - ./mongodb_data:/data/db

secrets:
  secret_key:
    file: ./secret_key
  password:
    file: ./password
  username:
    file: ./username