services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/components
          target: /usr/src/app/components
        - action: sync
          path: ./frontend/pages
          target: /usr/src/app/pages
        - action: rebuild
          path: ./frontend/package.json
          target: /usr/src/app/package.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - secret_key
        - password
        - username
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /code/app
        - action: rebuild
          path: ./backend/requirements.txt
          target: /code/requirements.txt

secrets:
  secret_key:
    file: ./secret_key
  password:
    file: ./password
  username:
    file: ./username