services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/components
          target: /usr/src/app/components
        - action: sync
          path: ./frontend/pages
          target: /usr/src/app/pages
        - action: rebuild
          path: ./frontend/package.json
          target: /usr/src/app/package.json